typography_spectrum: 0.4760497594252229
color:
  brandStrength: 0.10680163162760437
  lightness: 0.6676230339799076
  saturation: 0.17827289085835218
  rhythmicContrast: 0.3635196224786341
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
layout_spectrum: 0.14129230473190546
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/bf556f84-c603-46c5-ba22-fe598aeaa632.png
name: The Landscape Studio
navigation:
  - name: 'My Perfect 24 Hours, If I Were a Teleporting Billionaire | Travel Away'
    id: 1e7dbfb5-0fd4-49c6-83f7-c449427071cf
    type: content
title: The Landscape Studio
description: Landscape Design & Architecture
