typography_spectrum: 0.4760497594252229
color:
  brandStrength: 0.10680163162760437
  lightness: 0.6676230339799076
  saturation: 0.17827289085835218
  rhythmicContrast: 0.3635196224786341
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
layout_spectrum: 0.14129230473190546
name: The Landscape Studio
navigation:
  - id: 1e7dbfb5-0fd4-49c6-83f7-c449427071cf
    url: >-
      2016-04-15-my-perfect-24-hours-if-i-were-a-teleporting-billionaire-or-t.html
    name: 'My Perfect 24 Hours, If I Were a Teleporting Billionaire | Travel Away'
    type: content
title: Landscape Design & Architecture
