typography_spectrum: 0.20674439310096204
color:
  brandStrength: 0.776474853977561
  lightness: 0.883079472463578
  saturation: 0.9999545116443187
  rhythmicContrast: 0.417588414857164
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
layout_spectrum: 0.8368851996492594
name: The Landscape Studio
navigation:
  - id: 1e7dbfb5-0fd4-49c6-83f7-c449427071cf
    url: >-
      2016-04-15-my-perfect-24-hours-if-i-were-a-teleporting-billionaire-or-t.html
    name: 'My Perfect 24 Hours, If I Were a Teleporting Billionaire | Travel Away'
    type: content
title: Landscape Design & Architecture
