typography_spectrum: 0.7160441742744297
color:
  brandStrength: 0.27037938963621855
  lightness: 0.9768129703588784
  saturation: 0.8981019733473659
  rhythmicContrast: 0.04429826606065035
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
layout_spectrum: 0.64890042017214
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/bf556f84-c603-46c5-ba22-fe598aeaa632.png
name: The Landscape Studio
navigation:
  - name: 'My Perfect 24 Hours, If I Were a Teleporting Billionaire | Travel Away'
    id: 1e7dbfb5-0fd4-49c6-83f7-c449427071cf
    type: content
title: The Landscape Studio
description: Landscape Design & Architecture
